# Creates a deployment of two replica haproxy instances
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  labels:
    app: haproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: HaProxyRepository:latest # need to put the full ECR image path here, should use versions
          ports:
            - containerPort: 80