# Creates a service to expose our deployment and load balance between instances
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  labels:
    run: haproxy
spec:
  ports:
    - port: 5000
      protocol: TCP
  selector:
    run: haproxy